#!/usr/bin/env bash

# --delete: delete extraneous files from dest dirs
# --force: force deletion of dirs even if not empty
# --dry-run: shows what's going to happen

if [[ -n "$1" && $1 == "staging" ]]; then
    echo "Deploying to Spaces Staging server"
    rsync -azP --exclude={.git,phploy,phploy.ini,.gitignore,sync}  -e ssh ./ ubuntu@18.233.62.218:/home/www/thespaces/wp-content/covers
elif [[ -n "$1" && $1 == "live" ]]; then
    echo "Deploying to Spaces Live server"
    rsync -azP --exclude={.git,phploy,phploy.ini,.gitignore,sync}  -e ssh ./ ubuntu@3.82.249.129:/home/www/wp-content/covers
else
    echo "No server found."
fi
